[project]
name = "mcp-weather"
version = "0.1.0"
description = "MCP Server and Client for Weather API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.21.2",
    "anthropic>=0.74.1",
    "python-dotenv>=1.2.1",
]

